### ISSUE TITLE
Soft finger model loading

### ISSUE THREAD

**Issue by lz1oceani** [haosulab/SAPIEN-Release#1]
The parameters like patchRadius, minPatchRadius are for the hole model or just the finger. Can I change these parameters after building the object? I find that the attributes of object do not contain patchRadius.

**Comment by lz1oceani** [comment]
I foud we cannot setup the contact model of the robot fingers. So I am wondering if we need to change the parameter of the objects instead.

**Comment by fbxiang** [comment]
soft finger model is supported on shapes. Refer to ActorBuilder class addXXXShape for details.
