### ISSUE TITLE
Velocity control

### ISSUE THREAD

**Issue by yamokosk** [haosulab/SAPIEN-Release#10]
First, thanks for this great library. Great work!

The documentation provides great examples of how to do position control using the built-in PhysX controllers (as well as custom controllers). But it looks like velocity control isn't fully exposed. Following the API calls, it seems as though [`setDriveVelocityTarget`](https://github.com/haosulab/SAPIEN-Release/blob/0e0545ad19476774d48f0cfbd63420f99f79659e/src/articulation/sapien_joint.h#L71) needs to be exposed much like [`setDriveTarget`](https://github.com/haosulab/SAPIEN-Release/blob/0e0545ad19476774d48f0cfbd63420f99f79659e/src/articulation/sapien_joint.h#L74) is exposed via [`setDriveTarget`](https://github.com/haosulab/SAPIEN-Release/blob/0e0545ad19476774d48f0cfbd63420f99f79659e/src/articulation/sapien_articulation.h#L61) in `SArticulation`. I can submit a PR for this, but is there anything I am missing?

**Comment by fbxiang** [comment]
The setDriveVelocityTarget is currently exposed as joint.set_drive_velocity_target. For drive formula you can take a look at PhysX documentation [here](https://gameworksdocs.nvidia.com/PhysX/4.1/documentation/physxguide/Manual/Joints.html#drives).
