### ISSUE TITLE
Set gravity in a scene

### ISSUE THREAD

**Issue by poisonwine** [haosulab/SAPIEN-Release#11]
Sapien version: 0.7.0.dev0
system: Ubuntu16.04
When I want to set gravity in a scene,  I use sapien.engine.create_scene(gravity =[0,0,-2])  but get the TypeError:

TypeError: create_scene(): incompatible function arguments. The following argument types are supported:
    1. (self: sapien.core.pysapien.Engine, config: sapien.core.pysapien.SceneConfig = <sapien.core.pysapien.SceneConfig object at 0x7f92ec7b6928>) -> sapien.core.pysapien.Scene
Invoked with: <sapien.core.pysapien.Engine object at 0x7f92f2338fb8>; kwargs: gravity=[0, 0, -2]

Why would this happen and how can I solve this problem?

**Comment by fbxiang** [comment]
It appears part of the documentation is outdated, we will work on updating it soon. Currently you need to use the scene config for setting gravity.
```
sceneConfig = sapien.SceneConfig()
sceneConfig.gravity = [0, 0, -2] 
scene = engine.create_scene(config=sceneConfig)

```

**Comment by poisonwine** [comment]
Thanks a  lot.  It works fine.

**Comment by poisonwine** [comment]
By the way , what's the difference between builder.build(is_kinematic=True) and builder.build_static()?

**Comment by fbxiang** [comment]
Kinematic objects can move (so you can set their pose and velocity). They are essentially dynamic objects with infinite mass. Static objects are always static, so you can expect them to be faster to simulate in general.

**Comment by poisonwine** [comment]
Thanks a lot.And I have another question.I want to use ray-tracing in a scene,What are the configuration requirements of the graphics card? And is there any guidelines of building source code?

**Comment by fbxiang** [comment]
For ray tracing, you will need a Nvidia card (at least GTX 10XX), and Nvidia driver version 450+. For the 430-445 range, there are issues that affect our code in the driver that come and go in different versions, so 450+ is preferred just to be safe. To build a wheel with ray tracing support, you can simple use the script `docker_build_wheels_optix.sh`.

**Comment by poisonwine** [comment]
Ok，by the way, which version of Vulkan SDK should I install?

**Comment by poisonwine** [comment]
I follow the Cmake step to build Sapien.
the cmake results seem to be successful:

- RELEASE Build
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
-- pinocchio FOUND. pinocchio at /opt/openrobots/lib/libpinocchio.so
-- boost_filesystem FOUND. boost_filesystem at /usr/lib/x86_64-linux-gnu/libboost_filesystem.so
-- boost_serialization FOUND. boost_serialization at /usr/lib/x86_64-linux-gnu/libboost_serialization.so
-- boost_system FOUND. boost_system at /usr/lib/x86_64-linux-gnu/libboost_system.so
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   filesystem
--   serialization
--   system
-- hpp-fcl FOUND. hpp-fcl at /opt/openrobots/lib/libhpp-fcl.so
-- Boost version: 1.65.1
-- Compiling with OptiX
-- pybind11 v2.5.dev1
-- RELEASE Build
-- Profiler Off
Your ROS version not supported. Please update to kinetic or above.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xj/Documents/ydy/SAPIEN-Release/build

But When I use 'make'  to continue, it fails and I don't know how to solve this problem.
 [  0%] Built target glsl
[  0%] Building CXX object 3rd_party/sapien-vulkan/CMakeFiles/sapien-vulkan.dir/src/camera.cpp.o
...........
3rd_party/sapien-vulkan/CMakeFiles/sapien-vulkan.dir/build.make:62: recipe for target '3rd_party/sapien-vulkan/CMakeFiles/sapien-vulkan.dir/src/camera.cpp.o' failed
make[2]: *** [3rd_party/sapien-vulkan/CMakeFiles/sapien-vulkan.dir/src/camera.cpp.o] Error 1
CMakeFiles/Makefile2:1800: recipe for target '3rd_party/sapien-vulkan/CMakeFiles/sapien-vulkan.dir/all' failed
make[1]: *** [3rd_party/sapien-vulkan/CMakeFiles/sapien-vulkan.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by poisonwine** [comment]
the errors are shown in the picture below

https://github.com/poisonwine/hw5/blob/master/Screenshot%20from%202020-11-13%2020-24-50.png

**Comment by fbxiang** [comment]
Please build SAPIEN inside our Docker. Simply run `docker_build_wheels_optix.sh`. There are some package dependencies in SAPIEN that is hard to resolve, so the supported way to build from source is to use our docker environment.

**Comment by poisonwine** [comment]
@fbxiang  I follow your suggestion and successfully build the source code. Should I directly use wheelhouse's  *.whl file to install sapien(pip install  *.whl)?
