### ISSUE TITLE
Intended functionality of getActiveJoints?

### ISSUE THREAD

**Issue by yamokosk** [haosulab/SAPIEN-Release#12]
[`getActiveJoints`](https://github.com/haosulab/SAPIEN-Release/blob/0e0545ad19476774d48f0cfbd63420f99f79659e/src/articulation/sapien_articulation.cpp#L242) seems to have a bug in it. It appears as though the intent is to return just the joints that have dof > 0. But because of the use of [`push_back`](https://github.com/haosulab/SAPIEN-Release/blob/0e0545ad19476774d48f0cfbd63420f99f79659e/src/articulation/sapien_articulation.cpp#L246), the returned vector if full of a bunch of invalid, null joint pointers plus the "active" joints pushed onto the vector.

**Comment by fbxiang** [comment]
I believe that behavior is fixed in the latest version. If you are on the latest version, could you provide some code to reproduce the error?
