### ISSUE TITLE
Trouble downloading the dataset

### ISSUE THREAD

**Issue by PrabhjotKaurGosal** [haosulab/SAPIEN-Release#14]
**System:**
 - OS version: [Ubuntu 20.04]
 - Python version : [Python 3.8]
 - SAPIEN version (pip freeze | grep sapien): 
 - Environment: [Desktop]

**Describe the bug**
I am getting the following error when downloading the dataset. 
NameError   Traceback (most recent call last)
<ipython-input-9-44dcd92a3896> in <module>
----> 1 urdf = download_partnet_mobility(sapien_assets_id, token=my_token)
NameError: name 'download_partnet_mobility' is not defined

**To Reproduce**
Steps to reproduce the behavior (use pastebin for code):
1.  Pip install sapien and then follow the download steps on the Sapein website
2. import sapien
my_token = "my token in quotes"
sapien_assets_id = 179
urdf = download_partnet_mobility(sapien_assets_id, token=my_token)

**Expected behavior**
Successful download of the partnet dataset

**Additional context**
I have successfully downloaded sapien using pip command into my virtual environment in Python. At the moment, my virtual environment has python = 3.8, sapien, requests modules.

**Comment by fbxiang** [comment]
As described on the download page,
you need to do 
sapien.asset.download_partnet_mobility(id, token),
as the Python language will not import functions automatically for you. I hope it solves your issue.
