### ISSUE TITLE
Unexpected Segmentation Fault

### ISSUE THREAD

**Issue by 78ij** [haosulab/SAPIEN-Release#16]
**System:**
 - OS version: Ubuntu 20.04
 - Python version (if applicable): Python 3.8
 - SAPIEN version (pip freeze | grep sapien): 0.7.1dev0
 - Environment: Desktop

**Describe the bug**
Running a minimum example makes the system gives Segmentation Fault immediately after the 'engine.create_scene()' function call.
Tried running sapien on VMWare Workstation Player 15, Windows subsystem for Linux(WSL) and a physical machine with GTX 1050, the outcomes are the same.

**The code**

```python
import sapien.core as sapien

engine = sapien.Engine()
renderer = sapien.VulkanRenderer()
engine.set_renderer(renderer)

scene0 = engine.create_scene()
scene0.set_timestep(1 / 240)
```

**Screenshots**
(Using chinese as ubuntu system language, so gets chinese 'segmentation fault' report.)
using optifuserrenderer:
![2021-03-03 19-40-32 的屏幕截图](https://user-images.githubusercontent.com/13299678/109800650-6cd81980-7c58-11eb-822b-d9bb09b8c78b.png)

using vulkanrenderer:
![2021-03-03 19-41-47 的屏幕截图](https://user-images.githubusercontent.com/13299678/109800719-84170700-7c58-11eb-9f57-06461bb79ef0.png)

**Comment by daerduoCarey** [comment]
I think this is not an error. This indicates that the program quits normally. You need to create a step loop to prevent the main thread from quitting:

while not renderer_controller.should_quit:
    scene0.update_render()
    scene0.step()
    renderer_controller.render()

**Comment by fbxiang** [comment]
This only happens when engine is deleted before a scene. And this will be fixed in our next release.

**Comment by 78ij** [comment]
Solved by adding some code according to @daerduoCarey 's comment. Thanks for your quick reply. I'm closing this issue.
