### ISSUE TITLE
Hardware requirement

### ISSUE THREAD

**Issue by xuanzhezhao** [haosulab/SAPIEN-Release#17]
Hi, thanks for your nice project. But I just wonder if there is any hardware requirement if I want to run Sapien(from source code), like recommended CPU or GPU.  Is it possible to run Sapien without GPU support?

**Comment by fbxiang** [comment]
You can run SAPIEN without creating a renderer, then GPU is not required.
I do not recommend building from source unless you need ROS. If for some reason you have to build from source, you should use docker_build_wheels.sh as the dependencies are complicated.

**Comment by xuanzhezhao** [comment]
Thanks for your advice,  I'll try to use the quick installation first.

Many thanks!
