### ISSUE TITLE
Vulkan ErrorInitializationFailed

### ISSUE THREAD

**Issue by liqi17thu** [haosulab/SAPIEN-Release#18]
**System:**
 - OS version: Ubuntu 18.04
 - Python version: Python 3.8.8
 - SAPIEN version: 0.8.0.dev
 - Environment: Server with xvfb

**Describe the bug**
It works fine with the OpenGL version of sapien, but when I switch to Vulkan, it reports:

`
RuntimeError: vk::PhysicalDevice::getSurfaceFormatsKHR: ErrorInitializationFailed
`

Any advice?

**Comment by fbxiang** [comment]
With the Vulkan-based renderer, you do not need xvfb (it can run without x server). What you need to do instead is to turn on off_screen_only in the constructor of VulkanRenderer.

**Comment by liqi17thu** [comment]
By turning offscreen_only on, I got this error:
`/workspace/glfw/src/vulkan.c:306: glfwCreateWindowSurface: Assertion 'window != ((void *)0)' failed.
`

**Comment by fbxiang** [comment]
Since you are running without display, you should not create a window (maybe check your code and make sure you do not see a line like `VulkanController(renderer)`)

**Comment by liqi17thu** [comment]
I see, but I indeed want to visualize the results to debug my code, is that possible?

**Comment by fbxiang** [comment]
Ideally you would just do it on your local machine. In a server environment, you can setup cameras and render to images and then view the images, but then you cannot interactively play with the UI. It is also possible to use a remote desktop environment such as VNC.

**Comment by liqi17thu** [comment]
My local machine is Macbook pro, and I can only install 0.6.0.dev for MacOS, which has no VulkanController.

**Comment by fbxiang** [comment]
The current release version cannot be built for MacOS. If you do not have a Linux machine, then you can only use the old OpenGL renderer. If you can wait, we are actually close to a major release that includes a new Vulkan renderer with support for MacOS.

**Comment by liqi17thu** [comment]
Got it, looking forward to the new release, and thanks for the quick reply!
