### ISSUE TITLE
Add proximity sensor?

### ISSUE THREAD

**Issue by MRzNone** [haosulab/SAPIEN-Release#19]
**Is your feature request related to a problem? Please describe.**
It is hard to implement behavior like suction cup where I only need a distance information along a ray. (Check is suction is successful via checking if proximity sensor detects any object; the V-Rep way).

**Describe the solution you'd like**
I would like a proximity sensor parameterized by pose, sensing distance and sensing volume. The sensor could be attached to body like cameras.  The sensor could return distance and the object ID if detected.  Please advise [PyRep proximity sensor](https://github.com/stepjam/PyRep/blob/master/pyrep/objects/proximity_sensor.py)

**Describe alternatives you've considered**
Camera with 1x1 resolution.

**Additional context**
Trying to implement [this](https://github.com/stepjam/PyRep/blob/master/pyrep/robots/end_effectors/baxter_suction_cup.py).

**Comment by fbxiang** [comment]
Similar behavior will soon be possible using trigger shapes 
https://gameworksdocs.nvidia.com/PhysX/4.1/documentation/physxguide/Manual/RigidBodyCollision.html#trigger-shapes
which will be available in our next release (which should come next week)

For raycast-like behavior, it may be implemented in a future release.

**Comment by MRzNone** [comment]
Thanks for the timely response. You are awesome. This is awesome.
