### ISSUE TITLE
Error (cannot build dynamic articulation with more than 64 links) when loading some instances with loader.load_kinematic(urdf_path)

### ISSUE THREAD

**Issue by HelinXu** [haosulab/SAPIEN-Release#29]
**System:**
 - OS version: MacOS Big Sur
 - Python version (if applicable): Python 3.8.10
 - SAPIEN version (pip freeze | grep sapien): sapien==1.0.0rc2

**Describe the bug**
I downloaded the script from https://sapien.ucsd.edu/docs/latest/tutorial/rendering/camera.html and modified the index of the instance and got a bug.
original:
```
    loader = scene.create_urdf_loader()
    loader.fix_root_link = True
    urdf_path = '../assets/179/mobility.urdf'
    # load as a kinematic articulation
    asset = loader.load_kinematic(urdf_path)
    assert asset, 'URDF not loaded.'
```
mine:
```
    loader = scene.create_urdf_loader()
    loader.fix_root_link = True
    urdf_path = '../assets/13027/mobility.urdf'
    # load as a kinematic articulation
    asset = loader.load_kinematic(urdf_path)
    assert asset, 'URDF not loaded.'
```
and I got this message:

> [2021-07-07 14:14:52.532] [SAPIEN] [error] cannot build dynamic articulation with more than 64 links
> [1]    35806 segmentation fault  /opt/anaconda3/envs/detection/bin/python 

It seems that `asset = loader.load_kinematic(urdf_path)` does not work.

This is the 13027 folder in the dataset (which contains a keyboard with 100+ parts)
![image](https://user-images.githubusercontent.com/59716259/124719065-54934680-df39-11eb-82c9-2274423dde84.png)

I observed this error when there are too many parts in one instance, and I have not been able to render images for many instances in the Keyboard category. How can I fix that problem?

Thanks!

**Comment by fbxiang** [comment]
Thanks for the report and it has been fixed and pushed to https://github.com/haosulab/SAPIEN-Release/tree/nightly
You can build the Linux version with `docker_build_wheels.sh` immediately.
Mac version will need to wait for the next release, which should happen in about a week.

**Comment by HelinXu** [comment]
Thanks for updating!

However, I tried this version on my Ubuntu server as well as my Macbook:

```
git submodule update --init --recursive  
sudo ./docker_build_wheels.sh    

Release Mode
Using bin path /opt/python/cp36-cp36m/bin/python
Using include path /opt/python/cp36-cp36m/include/python3.6m
Running command 
====================Version Data====================
Git Revision Number: 60553ec95809a028c0c1554ac091155e144d51c3
Git Branch: nightly
Build Datetime: ********
Version Number: change_me_at_build_time
Host Name: ********
====================================================

```
 I ended up receiving the following error:

`auditwheel: error: cannot access ./dist/sapien-change_me_at_build_time-cp39-cp39-linux_x86_64.whl. No such file
`

![image](https://user-images.githubusercontent.com/59716259/125049820-f51d6e00-e0d3-11eb-95b5-efa5ea1cd751.png)

How can I fix that? Thanks!

**Comment by fbxiang** [comment]
Changing the content of `/python/VERSION` to an actual version number (e.g. 1.0, 2.0) should probably fix the issue.

**Comment by HelinXu** [comment]
Thanks, I am able to build SAPIEN on my server.

However, I get the following error when running the 'camera.py' from  https://sapien.ucsd.edu/docs/latest/tutorial/rendering/camera.html .

> [1]    69322 segmentation fault (core dumped)  python camera_original.py

and it returns 139.

![image](https://user-images.githubusercontent.com/59716259/125189479-e0bfa980-e26a-11eb-9ae0-41e5078513ec.png)


I found that it was caused by this line:

`renderer = sapien.VulkanRenderer()`

How to fix it?

Thanks!

**Comment by fbxiang** [comment]
Do you mean a single line `renderer = sapien.VulkanRenderer()` crashes on your server? This has not happened to me. What is the hardware on your server? I have only tested with Nvidia GPU so far.

**Comment by HelinXu** [comment]
Yes. For example, with the following code:

```
    print('1')
    engine = sapien.Engine()
    print('2')
    renderer = sapien.VulkanRenderer()
    print('3')
    engine.set_renderer(renderer)
```

I got:

```
1
2
[2021-07-12 22:28:18.353] [svulkan2] [error] GLFW error: X11: The DISPLAY environment variable is missing
[2021-07-12 22:28:18.353] [svulkan2] [warning] Continue without GLFW.
[1]    88373 segmentation fault (core dumped)  python camera.py
```

('3' never got printed)

If I set offscreen_only=True:

```
    print('1')
    engine = sapien.Engine()
    print('2')
    renderer = sapien.VulkanRenderer(offscreen_only=True)
    print('3')
    engine.set_renderer(renderer)
```

I got:

```
1
2
[1]    88869 segmentation fault (core dumped)  /home/*****/miniconda3/envs/sapien/bin/python 
```

both returns 139.

I am using Nvidia GPU as well.

**Comment by fbxiang** [comment]
Does it also happen with the release version of SAPIEN? 
Yes - try install vulkan-utils and what is the result of `vulkaninfo`?
No - It does not make sense at all to me, but just in case, make sure you install the compiled wheels in the wheelhouse folder.

**Comment by HelinXu** [comment]
Yes. When I used the the release version of SAPIEN, I still got the error "segmentation fault" as shown above.

After I use the command `ssh -X` to connect with my server, install `vulkan-utils` and run `vulkaninfo`, it returns the error

```shell
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS32
[1]    157893 segmentation fault (core dumped)  vulkaninfo
```

However, when I run `dpkg --print-architecture`, it returns

```shell
amd64
```

And when I run `dpkg --print-foreign-architectures`, it returns

```shell
i386
```

Besides, when I change my code into

```python
renderer = sapien.VulkanRenderer(offscreen_only=True)
```

I still got the same error as shown above.

**Comment by fbxiang** [comment]
if `vulkaninfo` does not work, it means your driver is not configured properly for Vulkan and SAPIEN will certainly crash. However, I am not sure why your `vulkaninfo` tries to use AMD and Intel cards. Maybe you can try setting environment variable `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json` (Make sure this file actually exists, if not, you have an incomplete Nvidia driver installation), and test `vulkaninfo` and SAPIEN again.
