### ISSUE TITLE
About the Dataset

### ISSUE THREAD

**Issue by HelinXu** [haosulab/SAPIEN-Release#33]
Hi Fanbo,

I accidentally found that some instances in partnet-mobility dataset do not provide all the obj files needed.

For example, https://sapien.ucsd.edu/api/download/compressed/3593.zip?token={TOKEN} do not have `textured_objs/new-1.obj`, which is required by the `mobility.urdf`

What do I do with these instances?

**Comment by fbxiang** [comment]
Hi Helin,
These objects are actually not needed. This is probably an issue from
PartNet where certain objects contain 0 faces. We have removed these
objects but keep them in URDF for reference. SAPIEN simulator will ignore
these files and you do not need to worry about them.
Best,
Fanbo

**Comment by HelinXu** [comment]
Got it, thanks!
