### ISSUE TITLE
PartNet-Mobility dataset

### ISSUE THREAD

**Issue by ugurbolat** [haosulab/SAPIEN-Release#36]
Hi there,

Thanks for sharing the project and dataset.

I would like to visualize the PartNet similar to the browsing and controlling widgets you provided in [your website](https://sapien.ucsd.edu/browse) locally (possibly in Jupyter notebook) and render/take pictures from different views and different poses of the object parts.

Could you provide some leading points?

P.S. So far, I've gone through the rendering part in the tutorial documentation. However, it seems like most functionality is in the viewer that is embedded in Vulkan rendering. However, there are no controlling widgets that change the pose of the object parts.

**Comment by ugurbolat** [comment]
For those who are looking for only rendering URDF object models in PartNet-Mobility from different views and different part poses, they can check out the following works:

https://github.com/dragonlong/articulated-pose
https://github.com/halfsummer11/CAPTRA

**Comment by DJNing** [comment]
Could you be more specific?
