### ISSUE TITLE
Get segmentation for a moving link

### ISSUE THREAD

**Issue by ChicyChen** [haosulab/SAPIEN-Release#38]
I try to move a link by adjusting the joints, and I wish to get the segmentation mask for that specific moving link.
Is there any way to map an adjusted joint to a moving link, and then map the moving link's name to a specific label in the result of `camera.get_uint32_texture('Segmentation')` ?
Or is there's another way to reaching the goal?

When I do:
`camera.get_uint32_texture('Segmentation')
seg_array = np.array(seg_labels)
print(np.unique(seg_array[:,:,0]))` 
The output is a bit hard to understand how it is related to different links:
`[0 1 12 18 19 20 21 31]`
Also, sorry that I don't understand how the render of segmentation works in the source code.

I would be really appreciate if you can help. Thank you!

**Comment by fbxiang** [comment]
`link.id` will correspond to `seg_array[:,:,1]` while visual id corresponds to `seg_array[:,:,0]`. So you should have a correct mapping when using channel 1 of the segmentation texture.

**Comment by ChicyChen** [comment]
Thank you!
