### ISSUE TITLE
No matching distribution found for sapien

### ISSUE THREAD

**Issue by ZhangHanbo** [haosulab/SAPIEN-Release#5]
**System:**
 - OS version: MacOS Catalina / Ubuntu 20.04
 - Python version: Python 3.6
 - SAPIEN version: Default
 - Environment: Desktop

**Describe the bug**
When I input the command "pip install sapien" or "pip3 install sapien" whether in MacOS or Ubuntu, the related package cannot be found and installed, and the following errors occur:

ERROR: Could not find a version that satisfies the requirement sapien (from versions: none)
ERROR: No matching distribution found for sapien

I am wondering if there is something wrong with my system or python version?

**Comment by fbxiang** [comment]
Please try upgrading your pip version by "pip[3] install --upgrade pip" and then install SAPIEN. I also strongly recommend using Ubuntu 20.04 over MacOS as SAPIEN is currently much more stable on Linux. If you still cannot install SAPIEN after upgrading pip. Please give me more detailed description of your python environment, including python version, pip version, anaconda/miniconda/venv/virtualenv.

**Comment by ZhangHanbo** [comment]
> Please try upgrading your pip version by "pip[3] install --upgrade pip" and then install SAPIEN. I also strongly recommend using Ubuntu 20.04 over MacOS as SAPIEN is currently much more stable on Linux. If you still cannot install SAPIEN after upgrading pip, please give me more detailed description of your python environment, including python version, pip version, anaconda/miniconda/venv/virtualenv.

I just use the system python of Ubuntu 20.04, without anaconda/miniconda/venv/virtualenv.
Python version: 3.8.2
pip version: 20.2.3

Same error with previously mentioned

**Comment by fbxiang** [comment]
We have not supported Python 3.8 yet. We currently plan to release a new version in 10 days that comes with Python 3.8. As for now, you can install with latest pip in python 3.6/3.7.

**Comment by ZhangHanbo** [comment]
> We have not supported Python 3.8 yet. We currently plan to release a new version in 10 days that comes with Python 3.8. As for now, you can install with latest pip in python 3.6/3.7.

Yes, I tried python 3.7 and it works. Thanks.
