### ISSUE TITLE
Scenarios from paper

### ISSUE THREAD

**Issue by MohitShridhar** [haosulab/SAPIEN-Release#6]
Thanks for the great resource! 

Does this repo contain these scenes presented in the paper:
![image](https://user-images.githubusercontent.com/6535354/95616791-443c5280-0a1f-11eb-9275-c3f89e10c862.png)

Or do you have to manually populate all these objects/robots?

**Comment by fbxiang** [comment]
These are manually populated. This repo is only for the code of the simulation environment. You will need to download the objects from [https://sapien.ucsd.edu/](https://sapien.ucsd.edu/) and robots from robot manufactures. However, we do have some testing robots at [https://github.com/haosulab/SAPIEN-Release/tree/master/assets_local/robot](https://github.com/haosulab/SAPIEN-Release/tree/master/assets_local/robot)
