### ISSUE TITLE
 Foundation object exists already. Only one instance per process can be created.

### ISSUE THREAD

**Issue by poisonwine** [haosulab/SAPIEN-Release#7]
**System:**
 - OS version:  Ubuntu 16.04
 - Python version (if applicable): Python 3.6
 - SAPIEN version : 0.7.0.dev0
 - Environment:conda virtual envrionment

**Describe the bug**
   I generate the scene in a loop, and for every scene ,I load models to scene on by one,then I remove all the models and set scene=None. But in the third cycle,when I create scene, the program exits abnormally. The error messages are as follows.

[SAPIEN] [critical] Foundation object exists already. Only one instance per process can be created.
 [SAPIEN] [critical] Foundation destruction failed due to pending module references. Close/release all depending modules first.
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
**

**Comment by fbxiang** [comment]
Can you confirm you are not creating sapien.core.Engine twice? If so, can you give a small code snippet that reproduces the problem?

**Comment by poisonwine** [comment]
> Can you confirm you are not creating sapien.core.Engine twice? If so, can you give a small code snippet that reproduces the problem?

Oh thank you ,I actually create Engine() twice. Problem has fixed.
