### ISSUE TITLE
How does the simulator know model mass? 

### ISSUE THREAD

**Issue by poisonwine** [haosulab/SAPIEN-Release#8]
I load the ShapeNet models to the scene, and I noticed that models have  different masses, how does the simulator know each model's mass and inertia?

**Comment by fbxiang** [comment]
If no mass is provided, the simulator computes mass and inertia from a given density (which defaults to 1000). Note the engine always needs to compute a convex hull of the collision shape, so this inertial computation is possible.

**Comment by poisonwine** [comment]
> If no mass is provided, the simulator computes mass and inertia from a given density (which defaults to 1000). Note the engine always needs to compute a convex hull of the collision shape, so this inertial computation is possible.

Thanks a lot !
