### ISSUE TITLE
How to set the mass, friction, and ray-tracing option?

### ISSUE THREAD

**Issue by poisonwine** [haosulab/SAPIEN-Release#9]
I have some questions about SAPIEN:

1. I found a function named actor_builder.set_mass_and_inertia, but I am not sure what the second and third required parameter are. How should I use this function to define the mass?

2. I am wondering if it is possible to customize friction between objects in SAPIEN.

3. How should I enable ray-tracing in SAPIEN for scene rendering?

I have gone through the documents but cannot find the related APIs.

**Comment by fbxiang** [comment]
1. The second parameter is the local pose of center of mass. The position part is the local translation of the center of mass; the rotation part specifies the principle inertia axes. The third parameter is the principle inertia (eigenvalues of the rotational inertia matrix), which is a vector of length 3.
2. There is no way to use custom friction, but you can specify the friction coefficient of each added shape (which is averaged between contact objects)
3. You need to compile SAPIEN from source by specifying the library path of OptiX. If building with docker, you try the script docker_build_wheels_optix.sh

If you cannot find something in the documentation, you can have a look at the [pybind](https://github.com/haosulab/SAPIEN-Release/blob/master/python/pysapien_content.hpp) file, which can often give some good hints.

**Comment by poisonwine** [comment]
> 1. The second parameter is the local pose of center of mass. The position part is the local translation of the center of mass; the rotation part specifies the principle inertia axes. The third parameter is the principle inertia (eigenvalues of the rotational inertia matrix), which is a vector of length 3.
> 2. There is no way to use custom friction, but you can specify the friction coefficient of each added shape (which is averaged between contact objects)
> 3. You need to compile SAPIEN from source by specifying the library path of OptiX. If building with docker, you try the script docker_build_wheels_optix.sh
> 
> If you cannot find something in the documentation, you can have a look at the [pybind](https://github.com/haosulab/SAPIEN-Release/blob/master/python/pysapien_content.hpp) file, which can often give some good hints.

Another problem is that I found the collision model in SAPIEN is not accurate.

It seems that SAPIEN will automatically generate the minimum convex hull of the multi-convex collision model.

An example:
https://github.com/poisonwine/hw5/blob/master/banan.collision.png
https://github.com/poisonwine/hw5/blob/master/banana.png

Is there any way to improve the collision model loaded by SAPIEN?

**Comment by fbxiang** [comment]
If your model file contains multiple convex objects (instead of a single non-convex object), you can use builder.add_multiple_convex_shapes_from_file to add them separately.
There will be no way to simulate non-convex shapes in SAPIEN. You will need to either manually model the object as combination of convex objects or use approximate algorithms such as V-HACD to decompose the objects into convex objects.

**Comment by ZhangHanbo** [comment]
> If your model file contains multiple convex objects (instead of a single non-convex object), you can use builder.add_multiple_convex_shapes_from_file to add them separately.
> There will be no way to simulate non-convex shapes in SAPIEN. You will need to either manually model the object as combination of convex objects or use approximate algorithms such as V-HACD to decompose the objects into convex objects.

Hello, I have the same problem. Will SAPIEN in the future support VHACD integration?

**Comment by fbxiang** [comment]
As parameters of VHACD are very application specific, and the results of VHACD

**Comment by poisonwine** [comment]
I also have a problem on Sapien builder when build ShapeNetCore.v2 models:

I use sapien.buider.add_visual_from_file('model_normalized.obj') to build ShapeNetCore.v2 models, and use VHACD to get models' multiple convex hull in the form of 'collision.obj', then build model with sapien.builder.add_multiple_convex_shapes_from_file('collision.obj'). But sapien give me warnings :

[Optifuser] [warning] A face with 2 indices is ignored in file: /home/data/ShapeNetCore.v2/03790512/cdd1e5890e5a766a65397d05162306e/models/model_normalized.obj 

And I found that plenty of models have the same warning. It seems that sapien can't regonize the face form which has 2 indices.
So I want to know will this problem affect model's physical feature when load into sapien scene?

**Comment by fbxiang** [comment]
2 indices will not form a face, it is at most a line. SAPIEN recognizes this case and ignores it. VHACD can sometimes produce 2-indices shapes or shapes with co-planar geometry, I recommend doing some pre-processing to clean up such cases. However, as long as SAPIEN gives a warning, such ill-formed geometry will be safely ignored in simulation.

**Comment by poisonwine** [comment]
I checed the modle _nomalized.obj file which causes warning and find that there are quite a  few forms like   this

# Mesh 'mesh5_mesh5-geometry' with 23 faces
g mesh5_mesh5-geometry
usemtl material_3_0
l  160 131
l  160 76
l  131 158
l  156 131
l ......
         it seems that the form 'l  v1 v2' causes the sapien's  warning. So  I want to know whether this form will actually cause sapien's  warning .
The model_normalize.obj file which causes sapien's warning  is here.(https://github.com/poisonwine/hw5/blob/master/model_normalized.obj)

**Comment by fbxiang** [comment]
Giving warnings for edges is intended behavior in SAPIEN. You can ignore the warnings or remove the edges from the file.

**Comment by chaoyivision** [comment]
Hi fb, I received the following warning with SAPIEN-v2.0 & PartnetMobility dataset.
**[2021-07-19 23:24:46.468] [SAPIEN] [warning] Mass or inertia contains very small number, this is not allowed. Mass will be set to 1e-6 and inertia will be set to 1e-8 for stability. Link: base
[2021-07-19 23:24:46.476] [SAPIEN] [warning] Mass or inertia contains very small number, this is not allowed. Mass will be set to 1e-6 and inertia will be set to 1e-8 for stability. Actor: **

I wonder whether there could be anyway to set these parameters for this dataset - or may I safely ignore them? If so, may I ask how to omit these warning messages (instead of printing them for each sample loaded). Thanks and Best,

**Comment by fbxiang** [comment]
enigne.set_log_level(“error”) turns off warnings.

**Comment by chaoyivision** [comment]
Many thanks fb! May I also have your confirmation on regarding the below sapien upgrade renaming when you are convinient?
PREV: camera.get_segmentation() => NOW: camera_instance.get_uint32_texture('Segmentation’)[…,0] (The MESH-LEVEL segmentation mentioned in SAPIEN-Camera document)
PREV: camera.get_obj_segmentation() => NOW: camera_instance.get_uint32_texture('Segmentation’)[…,1] (The ACTOR-LEVEL segmentation mentioned in SAPIEN-Camera document)

**Comment by fbxiang** [comment]
The previous obj segmentation is the mesh level segmentation, not actor
level. You can also verify by yourself by comparing the actor id and
segmentation id.
